### ISSUE TITLE
Suppressed children showing in collection tree

### ISSUE THREAD

**Issue by jamesgorrie** [wellcomecollection/catalogue#945]
When viewing a work that has children that are suppressed, they are still rendered in the collection tree:

__Parent:__ https://wellcomecollection.org/works/pzfpc7hx
__Suppressed child:__ https://wellcomecollection.org/works/xxaqfkcs 

![suppressed](https://user-images.githubusercontent.com/31692/95751480-933fed00-0c96-11eb-9ff2-fc3caa46b4fe.png)

**Comment by pollecuttn** [comment]
Clicking the link of the item that should be suppressed takes you through to an error page, not to the suppressed item.

**Comment by warrd** [comment]
Adding a filter for `type = "Visible"` here should fix this issue: https://github.com/wellcomecollection/catalogue/blob/master/api/api/src/main/scala/uk/ac/wellcome/platform/api/services/RelatedWorkRequestBuilder.scala#L89-L94

**Comment by pollecuttn** [comment]
@warrd what needs to happen for this to take effect, now that the issue is closed? I can currently still see the child record link in the parent record.

**Comment by warrd** [comment]
I didn't close the issue, apparently it did automatically when I merged the PR (not sure that should be the case).
